dump = (fileName) ->
  $.get fileName, ((data) ->
    console.log 'Probanbo probando'
    $('#INPUT').val data
    return
  ), dataType = 'text'
  return

handleFileSelect = (evt) ->
  evt.stopPropagation()
  evt.preventDefault()
  files = evt.dataTransfer.files
  # FileList object.
  reader = new FileReader
  reader.readAsText files[0], 'UTF-8'

  reader.onload = (e) ->
    textoTmp = ''
    textoTmp += e.target.result
    $('#INPUT').val textoTmp
    #console.log("Probando drag/drop -> " + textoTmp);
    return

  # files is a FileList of File objects. List some properties.
  #var template = _.template(usageList.innerHTML);
  #document.getElementById('list').innerHTML = template({ files : files});
  #evt.target.style.background = "black";
  return

handleDragOver = (evt) ->
  evt.stopPropagation()
  evt.preventDefault()
  evt.target.style.background = 'purple'
  return

setupFileList = ->
  # Setup the drag and drop listeners.
  dropZone = document.getElementById('drop_zone')
  dropZone.addEventListener 'dragover', handleDragOver, false
  dropZone.addEventListener 'drop', handleFileSelect, false
  return

# ---
# generated by js2coffee 2.0.3
