_ = require('underscore')
$ = require('jquery')
require("coffee-script")
logger = require('morgan')
cookieParser = require('cookie-parser')
bodyParser = require('body-parser')
express = require('express')
app = express()
module.exports = app
path = require('path')
app.set 'port', process.env.PORT or 5000
app.set 'views', path.join(__dirname, 'views')
app.set 'view engine', 'jade'
app.use logger('dev')
app.use bodyParser.json()
app.use bodyParser.urlencoded(extended: false)
app.use cookieParser()

app.use express.static(__dirname + '/')
app.get '/', (request, response) ->
  response.render 'index', title: 'Analiz. Lex. JS'
  return
app.listen app.get('port'), ->
  console.log 'Node app is running at localhost:' + app.get('port')
  return
app.get '/test/', (request, response) ->
  response.render 'test', title: 'Analiz. Lex. JS test'
  return


server = app.listen(3000, ->
  host = server.address().address
  port = server.address().port
  console.log 'Ex app list at https://%s:%s', host, port
  return
)

# ---
# generated by js2coffee 2.0.3
